version: "3.8"

networks:
  def_network:
    driver: bridge
    name: def_network

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api_service
    networks:
      - def_network

  api_service:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_service
    environment:
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis
    expose:
      - "9000"
      - "9003"
    ports:
      - "9003:9003"
    volumes:
      - ./api:/var/www/app:delegated
      - /var/www/app/vendor
    networks:
      - def_network

  auth_service:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth_service
    volumes:
      - ./auth:/var/www/app:delegated
      - /var/www/app/vendor
    expose:
      - "9000"
    environment:
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis
    networks:
      - def_network
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - def_network
